kind: pipeline
type: docker
name: default

steps:
- name: syntax-test
  image: saltstack/salt:latest
  commands:
    - salt-call state.show_sls formulas/common/base --states-dir=.

trigger:
  branch:
  - master
